services:
  db:
    image: postgres:18
    restart: always

    environment:
      POSTGRES_DB: minikms
      POSTGRES_USER: minikms
      POSTGRES_PASSWORD: minikms

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
